version: "3.9"
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/jorge/.config/firefox:/config
    ports:
      - 6001:3001
    shm_size: "1gb"
    restart: unless-stopped
  
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: vscode
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/jorge/.config/vscode:/config
    ports:
      - 6002:8443
    restart: unless-stopped