version: "3.9"
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - VERSION=docker
    volumes:
      - /var/lib/plex:/config
      - /mnt/SSD/media/plex/series:/tv
      - /mnt/SSD/media/plex/movies:/movies
      - /mnt/SSD/media:/media