version: "3.9"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:80/tcp"
    network_mode: bridge
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'Jm12345'
    volumes:
      - '/home/jorge/.config/pihole/etc:/etc/pihole'
      - '/home/jorge/.config/pihole/dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - TZ=Europe/Madrid
    volumes:
      - /home/jorge/.config/heimdall:/config
    ports:
      - 5000:80
    restart: unless-stopped
  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
    volumes:
      - /home/jorge/.config/qbittorrent:/config
      - /mnt/SSD/media:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBDOMAINS=keppler
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=false
    volumes:
      - /home/jorge/.config/duckdns:/config
    restart: unless-stopped
