version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "1000:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/config/portainer:/data
    restart: always