version: "3.9"
services:
  bitcoind:
    build: 
      context: .
      dockerfile: bitcoind.dockerfile
    container_name: bitcoind
    restart: always
    stop_grace_period: 15m
    ports:
      - "8332:8332"
      - "8333:8333"
    command:
      -txindex=1
      -blockfilterindex=1
      -peerblockfilters=1
      -peerbloomfilters=1
      -listen=1
      -port=8333
      -maxconnections=400
      -rpcbind=0.0.0.0
      -rpcport=8332
      -rpcallowip=0.0.0.0/0
      -rpcauth=jefe:a73a0f4133c04a64070b6befabe428ae$18650836a2dd47cd5be4e53ab2fc8044cc5fdd84fde961ae7fbf230487ac29ac
    volumes:
      - /home/jorge/.bitcoin:/root/.bitcoin

  electrs:
    build: 
      context: .
      dockerfile: electrs.dockerfile
    container_name: electrs
    restart: always
    stop_grace_period: 15m
    ports:
      - "50001:50001"
      - "4224:4224"
    environment:
      - ELECTRS_COOKIE_FILE=/data/.bitcoin/.cookie
      - ELECTRS_DAEMON_RPC_ADDR=bitcoind:8332
      - ELECTRS_DAEMON_P2P_ADDR=bitcoind:8333
      - ELECTRS_DB_DIR=/data
      - ELECTRS_NETWORK=bitcoin
      - ELECTRS_ELECTRUM_RPC_ADDR=0.0.0.0:50001
      - ELECTRS_LOG_FILTERS=INFO
    volumes:
      - /home/jorge/.bitcoin:/data/.bitcoin:ro
      - /home/jorge/.electrs:/data

  explorer:
    build: 
      context: .
      dockerfile: explorer.dockerfile
    container_name: explorer
    restart: always
    ports:
      - "3002:3002"
    environment:
      - BTCEXP_HOST=0.0.0.0
      - BTCEXP_BITCOIND_HOST=bitcoind
      - BTCEXP_BITCOIND_COOKIE=/data/.bitcoin/.cookie
    volumes:
      - /home/jorge/.bitcoin:/data/.bitcoin:ro
