version: "3.9"
services:
  bitcoin-rpc:
    image: "ruimarinho/bitcoin-core:23.0"
    container_name: "bitcoind"
    restart: unless-stopped
    stop_grace_period: 10m
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - "./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf"
      - "$HOME/.bitcoin:/home/bitcoin/.bitcoin"