version: "3.9"
services:
  bitcoind:
    build: 
      context: .
      dockerfile: bitcoind.dockerfile
    container_name: bitcoind
    restart: always
    stop_grace_period: 15m
    ports:
      - "8332:8332"
      - "8333:8333"
    environment:
      - TZ=Madrid/Europe
    volumes:
      - /home/jorge/.bitcoin:/root/.bitcoin