version: "3.9"
services:
  bitcoind:
    build: 
      context: .
      dockerfile: bitcoind.dockerfile
    container_name: bitcoind
    restart: always
    stop_grace_period: 15m
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - /home/jorge/.bitcoin:/root/.bitcoin

  electrs:
    build: 
      context: .
      dockerfile: electrs.dockerfile
    container_name: electrs
    restart: always
    stop_grace_period: 15m
    ports:
      - "50001:50001"
    environment:
      - TZ=Europe/Madrid
    volumes:
      - /home/jorge/.bitcoin:/data/.bitcoin:ro
      - /home/jorge/.electrs:/data