version: "3.9"
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/jorge/.config/prometheus:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
      - ./dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000

networks:
  metrics:
    name: metrics
    driver: bridge

volumes:
  metrics:
    name: metrics
    driver: local