version: "3.9"
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    command:
      - '--port=1001'
      - '--store_container_labels=false'
      - '--allow_dynamic_housekeeping=false'
      - '--docker_only=true'
      - '--housekeeping_interval=15s'
      - '--enable_metrics=cpu,memory,network,diskIO'
      #- '--disable_metrics=advtcp,app,cpu_topology,cpuset,disk,hugetlb,memory_numa,oom_event,percpu,perf_event,process,referenced_memory,resctrl,sched,tcp,udp'
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /sys/fs/cgroup:/cgroup:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 1001:1001
    privileged: true
    healthcheck:
      disable: true
    restart: unless-stopped
    devices:
      - /dev/kmsg

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - metrics:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-oss:11.2.0
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
      - ./dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./dashboards:/var/lib/grafana/dashboards
    ports:
      - 1003:3000

volumes:
  metrics:
    name: metrics
    driver: local
